import { db } from './client';
import { exercise } from './schema';

export type Exercise = typeof exercise.$inferSelect;

const STARTER: { name: string; muscleGroup: string; pattern: string }[] = [
  { name: 'Press inclinado', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press inclinado con barra', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press banca', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press plano mancuerna', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Aperturas', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Fondos', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Cruces en polea', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press de pecho en máquina', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Contractora de pecho', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press cruzado en polea', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press declinado', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press Larson', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Pec fly en polea', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press militar', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Elevaciones laterales', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Elevación frontal con disco', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Elevación lateral inclinada', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Elevación lateral en máquina', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Cruce inverso en polea', muscleGroup: 'hombro', pattern: 'tiron' },
  { name: 'Remo al mentón', muscleGroup: 'hombro', pattern: 'tiron' },
  { name: 'Pájaros', muscleGroup: 'hombro', pattern: 'tiron' },
  { name: 'Press hombro en máquina', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Press militar con barra', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Elevaciones laterales en polea', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Elevación en Y en polea', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Press Arnold', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Aperturas inversas', muscleGroup: 'hombro', pattern: 'tiron' },
  { name: 'Press francés', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Press cerrado en banca', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Extensión tríceps polea', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Extensión tríceps sobre la cabeza', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Patada de tríceps', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Extensión tríceps unilateral', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Flexiones diamante', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Extensión tríceps en máquina', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Jalón al pecho', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Jalón neutro', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Jalón cerrado', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Jalón unilateral arrodillado', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo mancuerna', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo en T', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo en polea', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo barra', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo Pendlay', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Dominadas', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo Gironda', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo en máquina', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo croc', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo Meadows', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo invertido', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Pullover', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Pullover en polea', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Encogimiento de hombros', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Encogimiento en polea', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Face pull', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Encogimientos de Kelso', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Dominadas escapulares', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Curl bíceps', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl inclinado', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl concentrado', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl martillo', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl martillo en predicador', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl tumbado', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl Zottman inverso', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl en polea', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl predicador', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl con barra Z', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl Bayesiano', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl overhead en polea', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Sentadilla', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Sentadilla con pausa', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Hack squat', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Sentadilla frontal', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Sentadilla pendular', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Sentadilla en Smith', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Sentadilla sissy', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Nórdico inverso', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Prensa', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Peso muerto rumano', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Peso muerto', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Peso muerto con barra trap', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Peso muerto piernas rígidas', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Curl nórdico', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Curl femoral', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Curl femoral sentado', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Extensión cuádriceps', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Gemelo de pie', muscleGroup: 'gemelo', pattern: 'pierna' },
  { name: 'Gemelo en prensa', muscleGroup: 'gemelo', pattern: 'pierna' },
  { name: 'Gemelo sentado', muscleGroup: 'gemelo', pattern: 'pierna' },
  { name: 'Zancadas', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Sentadilla búlgara', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Hip thrust', muscleGroup: 'gluteo', pattern: 'pierna' },
  { name: 'Hip thrust en máquina', muscleGroup: 'gluteo', pattern: 'pierna' },
  { name: 'Hip thrust unilateral', muscleGroup: 'gluteo', pattern: 'pierna' },
  { name: 'Puente de glúteo', muscleGroup: 'gluteo', pattern: 'pierna' },
  { name: 'Subida al cajón', muscleGroup: 'gluteo', pattern: 'pierna' },
  { name: 'Hiperextensión 45°', muscleGroup: 'gluteo', pattern: 'pierna' },
  { name: 'Patada de glúteo', muscleGroup: 'gluteo', pattern: 'pierna' },
  { name: 'Abducción de cadera', muscleGroup: 'gluteo', pattern: 'pierna' },
  { name: 'Crunch', muscleGroup: 'core', pattern: 'otro' },
  { name: 'Crunch declinado', muscleGroup: 'core', pattern: 'otro' },
  { name: 'Elevación de piernas', muscleGroup: 'core', pattern: 'otro' },
  { name: 'Rotación de torso', muscleGroup: 'core', pattern: 'otro' },
  { name: 'Plancha', muscleGroup: 'core', pattern: 'otro' },
  { name: 'Rueda abdominal', muscleGroup: 'core', pattern: 'otro' },
  { name: 'Colgarse en barra', muscleGroup: 'antebrazo', pattern: 'otro' },
  { name: 'Curl de muñeca', muscleGroup: 'antebrazo', pattern: 'otro' },
  { name: 'Curl inverso', muscleGroup: 'antebrazo', pattern: 'tiron' },
  { name: 'Extensión de muñeca', muscleGroup: 'antebrazo', pattern: 'otro' },
  // Ampliación catálogo (Fitness Park: máquinas de discos/selectorizadas, poleas, multipower y peso libre)
  { name: 'Flexiones', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press inclinado en máquina', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press en Smith', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press inclinado en Smith', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Press militar en Smith', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Elevación frontal con mancuerna', muscleGroup: 'hombro', pattern: 'empuje' },
  { name: 'Extensión tríceps cuerda', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Press francés con mancuerna', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Fondos en máquina', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Fondos en banco', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Remo bajo', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo bajo agarre supino', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Jalón supino', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Dominadas asistidas', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo Hammer', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Remo Dorian', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Encogimiento en máquina', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Curl con barra', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl araña', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Curl martillo en polea', muscleGroup: 'biceps', pattern: 'tiron' },
  { name: 'Prensa horizontal', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Aductor en máquina', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Sentadilla goblet', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Peso muerto sumo', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Zancada en Smith', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Gemelo en Smith', muscleGroup: 'gemelo', pattern: 'pierna' },
  { name: 'Patada de glúteo en máquina', muscleGroup: 'gluteo', pattern: 'pierna' },
  { name: 'Crunch en máquina', muscleGroup: 'core', pattern: 'otro' },
  { name: 'Elevación de piernas colgado', muscleGroup: 'core', pattern: 'otro' },
  { name: 'Plancha lateral', muscleGroup: 'core', pattern: 'otro' },
  // Ampliación 2 (huecos comunes tras cruzar con free-exercise-db)
  { name: 'Aperturas inclinadas', muscleGroup: 'pecho', pattern: 'empuje' },
  { name: 'Extensión tríceps polea agarre inverso', muscleGroup: 'triceps', pattern: 'empuje' },
  { name: 'Dominadas supinas', muscleGroup: 'espalda', pattern: 'tiron' },
  { name: 'Curl femoral de pie', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Buenos días', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Peso muerto con mancuernas', muscleGroup: 'pierna', pattern: 'pierna' },
  { name: 'Crunch en polea', muscleGroup: 'core', pattern: 'otro' },
  { name: 'Paseo del granjero', muscleGroup: 'antebrazo', pattern: 'otro' },
];

/** Asegura el catálogo: inserta los ejercicios del catálogo que falten (por nombre). */
export async function seedExercises(): Promise<void> {
  const existing = await db.select().from(exercise);
  const have = new Set(existing.map((e) => e.name));
  const missing = STARTER.filter((e) => !have.has(e.name));
  if (missing.length > 0) {
    await db.insert(exercise).values(missing.map((e) => ({ ...e, isCustom: false })));
  }
}

export async function listExercises(): Promise<Exercise[]> {
  return db.select().from(exercise);
}

export async function addExercise(name: string, muscleGroup: string, pattern: string): Promise<void> {
  await db.insert(exercise).values({ name, muscleGroup, pattern, isCustom: true });
}
