/**
 * Ficha técnica por ejercicio: "cómo hacerlo" en 2-4 claves cortas.
 * Sacado de la metodología aprobada (selección y técnica por músculo).
 * El lenguaje es de entrenador pero llano; los tecnicismos viven en el glosario.
 */
export interface ExerciseInfo {
  howTo: string[];
}

export const EXERCISE_INFO: Record<string, ExerciseInfo> = {
  // Pecho
  'Press inclinado': { howTo: ['Banco a 25–40° (no 45°, eso ya es hombro).', 'Retrae las escápulas y baja al pecho superior.', 'Empuja recto sin chocar arriba; no bloquees del todo los codos.'] },
  'Press banca': { howTo: ['Escápulas atrás y pies firmes en el suelo.', 'Baja la barra al pecho medio con control; codos ~45°.', 'Empuja sin rebotar; no bloquees los codos del todo.'] },
  'Press inclinado con barra': { howTo: ['Banco 25–40°; barra al pecho superior, en línea con el hombro.', 'Agarre algo más cerrado = más pecho superior y tríceps.', 'No empujes la barra hacia delante; sube recta o algo atrás.'] },
  'Press plano mancuerna': { howTo: ['Escápulas atrás; mancuernas a la altura del pecho.', 'Baja hasta notar estiramiento, codos ~45°.', 'Empuja en diagonal hacia dentro, sin chocarlas.'] },
  'Aperturas': { howTo: ['Codos semiflexionados y fijos todo el recorrido.', 'Abre hasta estirar (brazos algo por detrás del hombro).', 'Junta apretando el pecho, sin chocar las mancuernas.'] },
  'Fondos': { howTo: ['Inclina el torso adelante para cargar más pecho.', 'Hombros bajos, cuerpo en "flecha"; baja con control.', 'Sube sin bloquear; descanso 1,5–2 min.'] },
  'Cruces en polea': { howTo: ['Poleas altas; ligera inclinación al frente.', 'Codos semiflexionados fijos; junta abajo apretando.', 'Tensión constante: controla la vuelta.'] },
  'Press de pecho en máquina': { howTo: ['Te bloquea el patrón → gran conexión y bombeo; estira bien abajo.', 'Empuja sin bloquear del todo; controla la vuelta.', 'Seguro para ir al fallo (de los mejores para pecho).'] },
  'Contractora de pecho': { howTo: ['Pecho apoyado; junta los brazos apretando el pecho.', 'Codos algo flexionados y fijos; estira atrás al volver.', 'Estable y fácil de progresar.'] },
  'Press cruzado en polea': { howTo: ['Un brazo; presiona cruzando por delante, pasando la línea media.', 'Llega a la contracción final del pecho (que casi ningún ejercicio alcanza).', 'Tensión constante; controla la vuelta.'] },
  'Press declinado': { howTo: ['Banco declinado; baja al pecho inferior.', 'Codos ~45°, control en la bajada.', 'Alternativa "amable" a los fondos.'] },
  'Press Larson': { howTo: ['Como el press banca pero con las piernas en el banco (sin empuje de piernas).', 'Aísla más pecho/hombro/tríceps; agarre algo cerrado = más recorrido.', 'Tempo controlado 1–2 s; suele hacerse a ~75% de tu top set.'] },
  'Pec fly en polea': { howTo: ['Sentado y estable; codos semiflexionados y fijos.', 'Junta apretando el pecho; estira atrás al volver.', 'Tensión constante (mejor que de pie); gran aislamiento.'] },
  // Hombro
  'Press militar': { howTo: ['Nunca bloquees los codos arriba del todo.', 'De pie: escápulas atrás, pecho fuera, rodillas algo flexionadas.', 'Respaldo poco inclinado (más = se vuelve pecho).'] },
  'Elevaciones laterales': { howTo: ['Sube hasta la línea de los hombros, codos algo flexionados.', 'Lidera con el codo, no con la mano.', 'Baja lento; mejor sentado/apoyado para no balancear.'] },
  'Elevación frontal con disco': { howTo: ['Gira el disco como un volante (rotación interna) al subir → más deltoides medio.', 'Sube a la altura de los ojos; controla la bajada.', 'Si molesta el hombro, cámbiala por la elevación en Y.'] },
  'Elevación lateral inclinada': { howTo: ['Inclínate apoyado en un banco/rack; el brazo cuelga algo cruzado.', 'Así hay tensión en el estiramiento (abajo), no solo arriba.', 'Sube hasta la línea del hombro; baja lento.'] },
  'Elevación lateral en máquina': { howTo: ['Tensión suave y constante en todo el recorrido.', 'Lidera con el codo; controla la vuelta.', 'Muy fácil de progresar (sube peso o reps).'] },
  'Cruce inverso en polea': { howTo: ['Poleas cruzadas; barre los brazos hacia fuera (no tires hacia atrás).', 'Cruza los brazos arriba para más estiramiento del deltoides posterior.', 'Agarra el cable (no el agarre) para que deslice suave.'] },
  'Remo al mentón': { howTo: ['Mejor en polea con cuerda; sube barriendo los codos hacia fuera y arriba.', 'Trabaja deltoides lateral + trapecio.', 'Sin dolor de hombro; no subas demasiado el agarre.'] },
  'Pájaros': { howTo: ['Pecho apoyado o torso inclinado.', 'Brazos algo flexionados; abre en forma de "T".', 'Aprieta el deltoides posterior, sin tirar de trapecio.'] },
  'Press hombro en máquina': { howTo: ['Ajusta el asiento: agarres a la altura de los hombros.', 'Empuja sin bloquear; bajada controlada.', 'Ideal si tienes hombros delicados.'] },
  'Press militar con barra': { howTo: ['Barra desde las clavículas; aprieta glúteos y core.', 'Cabeza algo atrás para dejar pasar la barra.', 'Sube en línea recta; no arquees la lumbar.'] },
  'Elevaciones laterales en polea': { howTo: ['Sube barriendo hacia FUERA, no hacia arriba (no encojas el trapecio).', 'Polea alta = más difícil en el estiramiento; tensión constante.', 'Rango amplio, cruzando un poco el cuerpo.'] },
  'Aperturas inversas': { howTo: ['Máquina: brazos en "T", resistencia constante.', 'Aprieta el deltoides posterior.', 'Controla la vuelta.'] },
  'Press Arnold': { howTo: ['Empieza con las palmas hacia ti y gíralas a la vez que subes.', 'Aprieta glúteos y empuja con los talones (como un press militar).', 'Trabaja anterior + lateral; 8–10 reps cargando con cabeza.'] },
  'Elevación en Y en polea': { howTo: ['Cruza el brazo por delante del cuerpo abajo (estira el deltoides).', 'Sube en diagonal hacia fuera y arriba (forma de "Y"), no al frente.', 'Como "desenvainar una espada": tirón lateral, no elevación frontal.'] },
  // Tríceps
  'Press francés': { howTo: ['Codos quietos apuntando arriba.', 'Baja la barra a la frente/detrás con control (arco atrás = más estiramiento).', 'Extiende sin abrir los codos. (Favorito con barra Z.)'] },
  'Press cerrado en banca': { howTo: ['Agarre a la anchura de hombros; codos algo pegados.', 'Baja al pecho bajo; gran sobrecarga progresiva (cabezas lateral y media).', 'El tríceps largo se trabaja menos → combínalo con extensión overhead.'] },
  'Extensión tríceps polea': { howTo: ['Cuerpo recto, brazos pegados al torso.', 'Extiende abajo y aguanta; muñecas rectas.', 'Trabaja las cabezas lateral y media.'] },
  'Extensión tríceps sobre la cabeza': { howTo: ['Polea a la cintura; da un paso adelante e inclina.', 'Codos juntos en "V", rango amplio.', 'Enfatiza la cabeza larga.'] },
  'Patada de tríceps': { howTo: ['Codo fijo detrás del cuerpo, brazo en "V".', 'Solo mueve el antebrazo; torso quieto.', 'Aprieta arriba.'] },
  'Extensión tríceps unilateral': { howTo: ['Mancuerna sentado o polea; tensión en la negativa.', 'Solo se mueve el antebrazo.', 'Rango completo, control.'] },
  'Flexiones diamante': { howTo: ['Manos juntas en diamante bajo el pecho → más tríceps.', 'Cuerpo recto; baja controlando, no te dejes caer.', 'Genial como serie final al fallo (AMRAP).'] },
  'Extensión tríceps en máquina': { howTo: ['Asiento ajustado; extiende sin abrir los codos.', 'Aprieta abajo y controla la vuelta.', 'Estable y fácil de progresar (cabezas lateral y media).'] },
  // Espalda
  'Jalón al pecho': { howTo: ['Tira llevando los codos a los dorsales, no con los brazos.', 'Agarre medio/neutro; baja la barra al pecho alto.', '"Baja la barra", no "súbete tú"; controla la subida.'] },
  'Jalón neutro': { howTo: ['Agarre neutro/medio (manos enfrentadas) → más dorsal y cuida el hombro.', 'Tira con los codos hacia los dorsales, no con los brazos.', '"Baja la barra", no "súbete tú"; controla la subida.'] },
  'Jalón cerrado': { howTo: ['Agarre cerrado en triángulo → dorsal bajo.', 'Lleva el triángulo al pecho alto, codos pegados; saca pecho al final.', 'Estira arriba; controla la negativa.'] },
  'Jalón unilateral arrodillado': { howTo: ['Medio arrodillado, mano libre apoyada en la rodilla (base estable).', 'Para en la línea media (más atrás el dorsal pierde palanca).', 'Antebrazo en línea con el cable; controla la negativa.'] },
  'Remo mancuerna': { howTo: ['Codo pegado al torso, negativa lenta.', 'Recorrido completo; no te pares a la mitad.', 'Torso estable, sin balanceo.'] },
  'Remo en T': { howTo: ['Pecho sobre el apoyo (o bisagra estable, lumbar neutra); tira llevando los codos atrás.', 'Lleva el peso al abdomen y aprieta las escápulas.', 'Agarre neutro/cerrado = más dorsal; ancho = más espalda alta.'] },
  'Remo en polea': { howTo: ['Sentado; inclínate algo al frente en la negativa para estirar el dorsal.', 'Tira al abdomen llevando los codos atrás, sin balancear el torso.', 'Tensión constante; de los mejores para la espalda.'] },
  'Remo barra': { howTo: ['Torso a 30–45°, lumbar dentro (sin "modo trucha").', 'Lleva la barra al abdomen; codos en flecha.', 'Sin balanceo.'] },
  'Remo Pendlay': { howTo: ['Torso paralelo al suelo; cada rep parte del suelo.', 'Explosivo al subir, negativa controlada; en déficit (sobre un disco) estiras más.', 'Straps para que el agarre no limite la espalda.'] },
  'Dominadas': { howTo: ['Pecho a la barra (no solo barbilla); tira con la espalda, codos abajo y adentro.', 'Recorrido completo y control; sin balanceo (pausa abajo).', 'Progresa con lastre o reps; straps si el agarre limita.'] },
  'Remo Gironda': { howTo: ['Agarre cerrado/neutro; lleva al ombligo en horizontal.', 'Codos pegados; saca pecho al final.', 'Dorso recto.'] },
  'Remo en máquina': { howTo: ['Apoya el pecho en el respaldo (sin balanceo).', 'Tira llevando los codos atrás y aprieta las escápulas.', 'Varía el agarre entre series (ancho/cerrado/neutro) para toda la espalda.'] },
  'Remo croc': { howTo: ['Remo con mancuerna algo más erguido, con "trampa controlada".', 'Usa algo de impulso abajo (la espalda es fuerte ahí), pero controla la negativa.', 'Permite cargar más y llegar al fallo real del dorsal.'] },
  'Remo Meadows': { howTo: ['Landmine, una mano; apóyate y tira llevando el codo atrás.', 'Gran estiramiento abajo y mucha tensión en la espalda media.', 'Por lados; estable si te apoyas en la rodilla.'] },
  'Remo invertido': { howTo: ['Tú eres el peso: cuerpo recto, lleva el pecho a la barra.', 'Gran estiramiento abajo; cuanto más horizontal, más difícil.', 'Progresa con reps o lastre; sube la barra para asistir.'] },
  'Encogimiento en polea': { howTo: ['Encoge hacia arriba y hacia dentro (el trapecio superior abre en horizontal).', 'Cómodo y sin cargar discos; aprieta arriba.', 'Sin balancear.'] },
  'Pullover': { howTo: ['Estira los dorsales arriba con control.', 'Codos semifijos; lleva la mancuerna por encima.', 'Siente el estiramiento.'] },
  'Pullover en polea': { howTo: ['Polea alta; inclínate al frente en la bajada (estira el dorsal).', 'Lleva la cuerda/barra hacia las caderas bajando los codos (no con tríceps).', 'Reps algo más altas; aísla el dorsal sin fatiga general.'] },
  'Encogimiento de hombros': { howTo: ['Sube los hombros recto (sin rotar).', 'Ligera inclinación adelante; manos algo separadas.', 'Aprieta el trapecio arriba.'] },
  'Face pull': { howTo: ['Polea a la cara; tira llevando los codos atrás.', 'Brazos rectos (sin rotación) para alinear la fuerza.', 'Aprieta el deltoides posterior.'] },
  'Encogimientos de Kelso': { howTo: ['En remo con apoyo de pecho: retrae las escápulas.', 'Bloquea codos y mueve solo los omóplatos.', 'Para el trapecio medio.'] },
  'Dominadas escapulares': { howTo: ['Cuelga y deprime las escápulas (hombros lejos de las orejas).', 'Sin doblar codos; mueve solo los omóplatos.', 'Trapecio inferior y control escapular.'] },
  // Bíceps
  'Curl bíceps': { howTo: ['De pie, sin balanceo; bajada controlada.', 'Arco ligero hacia delante.', 'Supinación completa (palma arriba).'] },
  'Curl inclinado': { howTo: ['Brazo por detrás del cuerpo → cabeza larga.', 'Mantén la supinación desde el inicio.', 'Estira abajo, control.'] },
  'Curl concentrado': { howTo: ['Codo clavado (brazo por delante → cabeza corta).', 'Bajada lenta, sin balanceo.', 'Aprieta arriba.'] },
  'Curl martillo': { howTo: ['Agarre neutro → braquial (engorda el brazo).', 'Arco hacia delante, brazos rectos.', 'Bajada controlada.'] },
  'Curl martillo en predicador': { howTo: ['Agarre neutro apoyado en banco predicador → braquial con tensión en estirado.', 'No despegues el codo; estira abajo.', 'Engorda el brazo y "empuja" el pico del bíceps.'] },
  'Curl tumbado': { howTo: ['Tumbado boca arriba, brazos colgando atrás → estirón de la cabeza larga.', 'Sube curling sin mover el hombro.', 'Tensión en el estiramiento; cuida el hombro.'] },
  'Curl Zottman inverso': { howTo: ['Sube en martillo (braquial) y baja supinado (bíceps).', 'Aprovecha que bajas más fuerte: sobrecarga la negativa.', 'Control en la bajada.'] },
  'Curl en polea': { howTo: ['Tensión constante en todo el recorrido (de pie, brazos al lado).', 'Supina ("empuja con los meñiques"); control en la bajada.', 'Poco estiramiento inicial; combínalo con curls con el brazo atrás.'] },
  'Curl predicador': { howTo: ['Brazo apoyado por delante; no despegues el codo.', 'Estira abajo con control.', 'La mitad baja (estirada) es la que más crece.'] },
  'Curl con barra Z': { howTo: ['Barra Z para cuidar las muñecas; supina al subir.', 'Algo de impulso de cadera al inicio vale; controla la bajada.', 'Úsalo pesado a 6–8 reps (sobrecarga progresiva).'] },
  'Curl Bayesiano': { howTo: ['En polea, brazo por detrás del cuerpo → cabeza larga.', 'Tensión constante; supina desde el inicio.', 'Estira en el punto bajo.'] },
  'Curl overhead en polea': { howTo: ['Arrodillado, brazo a la altura del hombro y curl hacia la cabeza.', 'Sesga la cabeza larga (el "pico" del bíceps).', 'Tensión constante; control en la bajada.'] },
  // Pierna
  'Sentadilla': { howTo: ['Baja al menos a la paralela; más profundo = más estímulo y glúteo.', 'Empuja con los TALONES (línea vertical desde el talón); core firme.', 'Puntas algo hacia fuera y rodillas alineadas con ellas: que no se metan hacia dentro.', 'Principiante: hack o prensa, más estables.'] },
  'Sentadilla con pausa': { howTo: ['Pausa de 1–2 s abajo (sin rebote) y explota hacia arriba.', 'Barra recta sobre el medio del pie; ~75% de tu top set.', 'Asegura profundidad y técnica con menos carga.'] },
  'Hack squat': { howTo: ['Espalda apoyada; baja profundo (yoga blocks si no llegas).', 'Rodillas hacia las puntas.', 'Empuja con todo el pie. (De los mejores para cuádriceps.)'] },
  'Sentadilla frontal': { howTo: ['Barra al frente (sobre los hombros); torso erguido → más cuádriceps.', 'Codos arriba, baja entre las piernas, pecho alto.', 'Agarre limpio, cruzado o con straps; el que mejor sientas.'] },
  'Sentadilla pendular': { howTo: ['La carga sube/baja en arco (más natural que la hack).', 'Apóyate y baja profundo; empuja con todo el pie.', 'Muy estable: lleva el cuádriceps cerca del fallo sin miedo.'] },
  'Sentadilla en Smith': { howTo: ['Pies algo adelante; baja profundo sin miedo a caer.', 'Como la sentadilla libre con menos estabilización.', 'Puedes ir al fallo con seguridad.'] },
  'Nórdico inverso': { howTo: ['De rodillas, échate atrás bajando con control (estira el cuádriceps).', 'Sube apretando el cuádriceps; muy duro, empieza con poco rango.', 'En casa sin máquina; progresa con rango o disco al pecho.'] },
  'Prensa': { howTo: ['Pies a la anchura de hombros; baja con control.', 'No bloquees las rodillas arriba.', 'No despegues la lumbar del respaldo.'] },
  'Peso muerto rumano': { howTo: ['Enfoca isquios: estira en la bajada.', 'Barra cerca de las piernas; caderas atrás.', 'Sube empujando las caderas; lumbar neutra.'] },
  'Peso muerto': { howTo: ['Bisagra de cadera; barra pegada y recta sobre el medio del pie.', 'Pecho arriba, lumbar neutra; sube empujando el suelo.', 'Top set pesado (RPE 8–9); muy fatigante, dosifícalo.'] },
  'Peso muerto con barra trap': { howTo: ['Dentro de la barra hexagonal; torso más erguido → más cuádriceps.', 'Bisagra y empuje del suelo; lumbar neutra.', 'Alternativa más amable para la espalda.'] },
  'Peso muerto piernas rígidas': { howTo: ['Caderas altas y rodillas casi rectas; bisagra de cadera.', '~50–60% del top set; estira isquios sin forzar el rango al inicio.', 'Controla la negativa.'] },
  'Curl nórdico': { howTo: ['Tobillos fijos; baja resistiendo al máximo (negativa).', 'Empuja con las manos abajo para volver arriba.', 'Isquios; muy duro, empieza con asistencia.'] },
  'Curl femoral': { howTo: ['Empuja las caderas contra el banco (no las dejes subir).', 'Rango completo; parciales en el estiramiento al final del set.', 'Tumbado también trabaja el sartorio; alterna con el sentado en la semana.'] },
  'Curl femoral sentado': { howTo: ['Mejor que tumbado: más estiramiento del isquio.', 'Torso adelante hasta notar tensión antes de empezar.', 'Puntas hacia dentro = isquio interno; hacia fuera = externo.'] },
  'Extensión cuádriceps': { howTo: ['El único donde el recto femoral trabaja bien (cadera fija): NO te inclines adelante, recline el asiento atrás para estirarlo.', 'Rodillas en el borde del asiento, rodillo bien metido; agárrate fuerte para estabilizar.', 'No es lesivo: si molestan las rodillas, baja peso y sube reps (10–15), rango completo y lento.', 'Sube y aprieta arriba; negativa controlada.'] },
  'Sentadilla sissy': { howTo: ['Cadera quieta y rodillas viajando al frente: estira el recto femoral (como la extensión).', 'Échate atrás bajando con control, agarrado para equilibrar.', 'Difícil; empieza con poco rango y progresa.'] },
  'Zancadas': { howTo: ['Baja lento, cuida la alineación de la rodilla.', 'Paso largo = más glúteo.', 'Elige la variante donde controles el equilibrio.'] },
  'Sentadilla búlgara': { howTo: ['Pie trasero elevado; baja recto.', 'Torso algo inclinado = más glúteo.', 'Controla el equilibrio.'] },
  'Gemelo de pie': { howTo: ['Superficie elevada; baja a un estiramiento profundo (lo que más crece).', 'Sube sobre los metatarsos, sin rebotes; control.', 'Truco: aguanta 30 s en el estiramiento al final del último set.'] },
  'Gemelo en prensa': { howTo: ['Sentado en la prensa, empuja con la punta; rango completo.', 'Aprieta arriba y estira abajo.', 'Puntas fuera = gemelo interno; dentro = externo; rectas = ambos.'] },
  'Gemelo sentado': { howTo: ['Rodilla flexionada → trabaja el sóleo; rango completo.', 'Aprieta arriba, estira abajo; reps altas.', 'Complementa al gemelo de pie (rodilla recta = gastrocnemio).'] },
  // Glúteo
  'Hip thrust': { howTo: ['Piernas a ≤90°, pies planos, torso recto.', 'Aprieta los glúteos arriba; core en tensión.', 'No curves la lumbar. Progresa subiendo peso (5–15 reps).'] },
  'Hip thrust en máquina': { howTo: ['Cinturón sobre la cadera; pies planos.', 'Empuja con los talones y aprieta el glúteo arriba.', 'Más cómodo y estable que con barra; gran progresión de peso.'] },
  'Hip thrust unilateral': { howTo: ['Una pierna; controla el equilibrio (enfatiza el glúteo superior).', '12–15 reps por lado, sin ir pesado.', 'Corrige descompensaciones izquierda/derecha.'] },
  'Subida al cajón': { howTo: ['Cajón a la altura de la rodilla o algo más alto.', 'Sube empujando con el talón, sin impulso de la otra pierna.', 'Inclínate algo al frente para cargar más glúteo que cuádriceps.'] },
  'Hiperextensión 45°': { howTo: ['Extiende la cadera; redondea un poco la espalda alta para sentir el glúteo.', 'Aprieta arriba sin hiperextender la lumbar.', 'Progresa con reps o sujetando un disco al pecho.'] },
  'Puente de glúteo': { howTo: ['En el suelo; aprieta los glúteos arriba.', 'Core firme; no arquees la lumbar.', 'En casa: con mancuerna sobre la cadera.'] },
  'Patada de glúteo': { howTo: ['En polea: patada en diagonal/abducción (no vertical).', 'Estabiliza el torso.', 'Aprieta el glúteo arriba.'] },
  'Abducción de cadera': { howTo: ['Inclinada al frente → glúteo mayor; en puente/caderas extendidas → glúteo medio.', 'Rango 90–45°; aprieta hacia fuera.', 'No vayas ligero: progresa de verdad (casi al fallo).'] },
  // Core
  'Crunch': { howTo: ['Recorrido completo: acerca las costillas a las caderas.', 'Flexiona la columna, no tires del cuello.', 'Añade peso para progresar.'] },
  'Crunch declinado': { howTo: ['Disco en el pecho; redondea la lumbar al subir (no flexiones solo la cadera).', 'Aprieta el abdomen; baja con control.', 'Progresa añadiendo peso o reps.'] },
  'Elevación de piernas': { howTo: ['Sube las piernas con control, sin balanceo.', 'Mantén el core en tensión.', 'Colgado o tumbado.'] },
  'Rotación de torso': { howTo: ['Trabaja oblicuos; gira desde el tronco.', 'Control, sin tirones.', 'Mantén la cadera estable.'] },
  'Plancha': { howTo: ['Cuerpo recto, glúteos y core apretados.', 'No hundas la cadera.', 'Respira y aguanta el tiempo objetivo.'] },
  'Rueda abdominal': { howTo: ['Rueda hacia delante estirando, sin arquear la lumbar.', 'Aprieta abdomen y glúteos todo el recorrido.', 'Empieza de rodillas con poco recorrido; progresa el rango.'] },
  // Antebrazo
  'Colgarse en barra': { howTo: ['Cuelga al fallo técnico (cuando se rompe la postura).', '2–3 series, descanso >2 min, al final de la rutina.', 'Cuando aguantes >1 min, añade peso.'] },
  'Curl de muñeca': { howTo: ['Antebrazo apoyado; flexiona solo la muñeca.', 'Reps altas (12–20), recorrido corto.', 'Control arriba y abajo.'] },
  'Curl inverso': { howTo: ['Agarre prono (pronación) → braquiorradial.', 'Reps altas; poco descanso.', 'Muñecas firmes.'] },
  'Extensión de muñeca': { howTo: ['Antebrazo apoyado; extiende la muñeca.', 'Reps altas (12–20).', 'Control en la vuelta.'] },
  // Ampliación catálogo (Fitness Park)
  Flexiones: { howTo: ['Cuerpo recto (plancha), manos a la anchura del pecho.', 'Baja con control hasta casi tocar; codos ~45°.', 'Sube sin hundir la cadera; añade lastre o déficit para progresar.'] },
  'Press inclinado en máquina': { howTo: ['Ajusta el asiento: agarres a la altura del pecho alto.', 'Empuja sin bloquear; controla la vuelta.', 'Estable y seguro para acercarte al fallo.'] },
  'Press en Smith': { howTo: ['Barra guiada al pecho medio; escápulas atrás.', 'Baja con control, codos ~45°; empuja recto.', 'Seguro para ir al fallo sin observador.'] },
  'Press inclinado en Smith': { howTo: ['Banco a 25–40° bajo la barra guiada.', 'Baja al pecho superior; no bloquees del todo.', 'Estable: progresa con peso o reps.'] },
  'Press militar en Smith': { howTo: ['Barra guiada desde las clavículas; aprieta core y glúteos.', 'Sube recto sin arquear la lumbar; no bloquees del todo.', 'Estable; bueno si tienes hombros delicados.'] },
  'Elevación frontal con mancuerna': { howTo: ['Sube al frente hasta la altura de los ojos.', 'Control en la bajada; sin balanceo.', 'Algo redundante si haces mucho press: úsala con cabeza.'] },
  'Extensión tríceps cuerda': { howTo: ['Cuerpo recto, codos pegados al torso.', 'Extiende abajo y separa las manos al final.', 'Cómoda para muñecas; más aislamiento.'] },
  'Press francés con mancuerna': { howTo: ['Tumbado o sentado; codos quietos apuntando arriba.', 'Baja la mancuerna tras la cabeza (estira la cabeza larga).', 'Extiende sin abrir los codos.'] },
  'Fondos en máquina': { howTo: ['Máquina asistida o de empuje; torso erguido = más tríceps.', 'Baja con control; sube sin bloquear.', 'Permite acercarte al fallo con seguridad.'] },
  'Fondos en banco': { howTo: ['Manos en el banco tras la espalda; flexiona los codos hacia atrás.', 'No bajes en exceso si molesta el hombro.', 'Pies más lejos = más dificultad; lastre en el regazo para progresar.'] },
  'Remo bajo': { howTo: ['Sentado en polea baja; pecho alto, lumbar neutra.', 'Tira al abdomen llevando los codos atrás y aprieta escápulas.', 'Estírate al frente con control (sin redondear); no balancees.'] },
  'Remo bajo agarre supino': { howTo: ['Polea baja, palmas hacia arriba → más dorsal bajo (y bíceps).', 'Lleva al abdomen con los codos pegados; aprieta atrás.', 'Controla la negativa estirando el dorsal.'] },
  'Jalón supino': { howTo: ['Agarre supino a la anchura de hombros → más dorsal bajo y bíceps.', 'Baja la barra al pecho llevando los codos abajo, no con los brazos.', 'Controla la subida; saca pecho al final.'] },
  'Dominadas asistidas': { howTo: ['Máquina con contrapeso (más peso seleccionado = más ayuda).', 'Pecho hacia la barra, codos abajo y adentro; control.', 'Reduce la asistencia conforme progresas.'] },
  'Remo Hammer': { howTo: ['Máquina de discos con pecho apoyado; tira de los codos atrás.', 'Aprieta las escápulas; no encojas los hombros.', 'Varía el agarre (neutro/pronado) entre series.'] },
  'Remo Dorian': { howTo: ['Barra con agarre supino (palmas arriba), torso a ~45°, lumbar neutra.', 'Lleva la barra al abdomen bajo con los codos pegados; algo de impulso controlado vale.', 'Negativa lenta; enfatiza el dorsal bajo.'] },
  'Encogimiento en máquina': { howTo: ['Sube los hombros recto, sin rotar.', 'Aprieta el trapecio arriba; baja con control.', 'Reps medias-altas; progresa de peso.'] },
  'Curl con barra': { howTo: ['De pie, supina; sube sin balancear (algo de impulso al inicio vale).', 'Baja con control (negativa).', 'Barra Z si molestan las muñecas.'] },
  'Curl araña': { howTo: ['Pecho apoyado en banco inclinado, brazos colgando al frente → cabeza corta.', 'Sube apretando arriba; codos quietos.', 'Tensión constante; bajada lenta.'] },
  'Curl martillo en polea': { howTo: ['Cuerda en polea baja, agarre neutro → braquial.', 'Sube en martillo; brazos rectos, sin balanceo.', 'Tensión constante; control en la bajada.'] },
  'Prensa horizontal': { howTo: ['Sentado; pies a la anchura de hombros, baja profundo con control.', 'No bloquees las rodillas; no despegues la lumbar del respaldo.', 'Empuja con todo el pie.'] },
  'Aductor en máquina': { howTo: ['Junta los muslos contra la resistencia (cara interna).', 'Rango completo: aprieta al juntar, estira al abrir.', 'Reps medias-altas; control.'] },
  'Sentadilla goblet': { howTo: ['Mancuerna/kettlebell pegada al pecho; baja entre las piernas.', 'Torso erguido, talones en el suelo; busca profundidad.', 'Buena para aprender el patrón o como finisher.'] },
  'Peso muerto sumo': { howTo: ['Piernas anchas, puntas hacia fuera; agarre dentro de las rodillas.', 'Pecho alto, lumbar neutra; empuja el suelo.', 'Más cadera/aductor y torso más erguido que el convencional.'] },
  'Zancada en Smith': { howTo: ['Barra guiada sobre los hombros; un pie adelantado.', 'Baja recto cuidando la rodilla; empuja con el talón.', 'Estable: céntrate en el rango y el equilibrio.'] },
  'Gemelo en Smith': { howTo: ['Puntas sobre un step bajo la barra guiada.', 'Estira abajo y sube sobre los metatarsos, sin rebotes.', 'Aguanta el estiramiento al final del set.'] },
  'Patada de glúteo en máquina': { howTo: ['Empuja con un pie extendiendo la cadera; torso fijo.', 'Aprieta el glúteo arriba; control en la vuelta.', 'Por lados; rango completo.'] },
  'Crunch en máquina': { howTo: ['Flexiona el tronco acercando costillas a caderas (no tires del cuello).', 'Aprieta el abdomen abajo; controla la vuelta.', 'Progresa con peso (sobrecarga, como cualquier músculo).'] },
  'Elevación de piernas colgado': { howTo: ['Colgado; sube curvando la pelvis (no solo flexión de cadera).', 'Sin balanceo; baja con control.', 'Rodillas flexionadas si no llegas con piernas rectas.'] },
  'Plancha lateral': { howTo: ['De lado, cuerpo recto, apoyado en antebrazo y pie.', 'Aprieta el oblicuo; no dejes caer la cadera.', 'Aguanta el tiempo objetivo por cada lado.'] },
};

export function exerciseInfo(name: string): ExerciseInfo | null {
  return EXERCISE_INFO[name] ?? null;
}
